default: &default
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: 10

development:
  <<: *default
  host: <%= ENV['DEV_DB_IP_ADDRESS'] %>
  username: <%= ENV['DEV_DB_USERNAME'] %>
  password: <%= ENV['DEV_DB_PASSWORD'] %>
  database: <%= ENV['DEVELOPMENT_DB'] %>

test:
  <<: *default
  host: <%= ENV['TEST_DB_IP_ADDRESS'] %>
  username: <%= ENV['TEST_DB_USERNAME'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>
  database: <%= ENV['TEST_DB'] %>

production:
  <<: *default
  host: <%= ENV['PROD_DB_IP_ADDRESS'] %>
  username: <%= ENV['PROD_DB_USERNAME'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
  database: <%= ENV['PRODUCTION_DB'] %>